name: Auto Ads Inject (DirectLink, light)

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.html"
      - "scripts/inject-ads.mjs"
      - ".github/workflows/auto-ads-inject.yml"
  schedule:
    # Nightly sweep to keep new pages up-to-date
    - cron: "17 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: site-writes
  cancel-in-progress: false

jobs:
  inject-ads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Inject/Update lightweight DirectLink ads
        env:
          DIRECT_LINK_URL: "https://otieu.com/4/9747938"
          DAILY_CAP: "2"          # per-device, per-day
          SHOW_PROB: "0.05"       # 5% on both desktop & mobile
          SKIP_PATHS: "admin/ads-status.html"
        run: node scripts/inject-ads.mjs

      - name: Commit & Push (rebase with autostash, safe for concurrent writes)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            # Rebase safely even if remote moved; autostash to avoid "unstaged changes" error
            git -c rebase.autoStash=true pull --rebase origin main || true

            git add -A
            git commit -m "ci(ads): inject/update lightweight DirectLink ad (5% w/ 2/day cap)"
            git push --force-with-lease origin HEAD:main
          else
            echo "No changes to commit."
          fi
