name: Build Sitemap

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "17 2 * * *"  # nightly 02:17 UTC
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate sitemap.xml
        env:
          SITE_URL: https://www.techability.co.nz
        run: |
          node scripts/generate-sitemap.mjs

      - name: Commit & Push sitemap
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add sitemap.xml
            git commit -m "ci(sitemap): update sitemap.xml"
            git push
          else
            echo "No changes to commit."
          fi
